### ISSUE TITLE
Can't download file 

### ISSUE THREAD

**Issue by Thanh96** [Xvier/cypress-downloadfile#1]
I finish steps flowing instruction but after running i had problem. Please review it and let me know how to fix them. Thanks
Cypress: 3.4.1 
![Screenshot 2019-10-30 11 43 53](https://user-images.githubusercontent.com/29529118/67829873-40176d80-fb0b-11e9-8051-8d6cebf93bcc.png)

**Comment by Xvier** [comment]
@Thanh96, can you give me more info so that i can help you. 
Can you share a piece of your code?

**Comment by Thanh96** [comment]
Thanks for your reply but i handled my problem.
Thanks again for your good library. :)
