### ISSUE TITLE
Parse Error: Header overflow

### ISSUE THREAD

**Issue by czende** [Xvier/cypress-downloadfile#16]
Hi, I'm using version 1.2.0 and Cypress version 5.2.0. Every attempt of file download ends up with the following error 

![Screenshot 2021-02-07 at 16 13 01](https://user-images.githubusercontent.com/5628485/107150737-95be0500-695f-11eb-97bf-75bacf151e1f.png)
any ideas? Thx!

**Comment by Xvier** [comment]
Hi @czende, I will try and recreate your problem with cypress 5.2.0.
Also on another note if you upgrade cypress to version 6.3.0 you get out-of-the-box download support. So the question is do you still want to use my plugin on a lower version of cypress or upgrade to a higher cypress version.

**Comment by czende** [comment]
Thank you for your answer. I didn't know that this is already presented in higher Cypress version. I'll try to upgrade, so this issue can be closed 👌

EDIT: arou you sure that in 6.3.0 is native download support? I cannot find anything about it in doc.

**Comment by Xvier** [comment]
@czende 

https://docs.cypress.io/guides/references/changelog.html#6-3-0

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the downloadsFolder which is set to cypress/downloads by default. The downloadsFolder will be deleted before each run unless trashAssetsBeforeRuns is set to false. Addresses #949.

**Comment by czende** [comment]
Thank you, I've tried to update Cypress and test file download and it seems to be fine until you want to do anything else after that. It's just waiting for page load and then timeouted. Related bug was already reported here https://github.com/cypress-io/cypress/issues/14857
