### ISSUE TITLE
if link avable for authorized users

### ISSUE THREAD

**Issue by RuslanAisin** [Xvier/cypress-downloadfile#18]
For download firstly I should authorized on page after that I use download and get 401 error. Is it possible to get auth and after download pdf?
![image](https://user-images.githubusercontent.com/49075028/129386624-d209528c-ebcf-4056-82bc-2e610c87b45c.png)
cypress 7.4.0 
browser chrome

**Comment by Xvier** [comment]
Hi @RuslanAisin, how is the auth being stored in the app you are testing? Since that also depends if I can help you or not.
Also next time will you please use the issue template so that I have more details.

**Comment by RuslanAisin** [comment]
Hello @Xvier, thank you for respose my issue.  I find another way to resolve my problem here https://docs.cypress.io/api/commands/request#Download-a-PDF-file
In my tests the Auth via ntlm auth - Microsoft sharepoint product. I suppose it is hard to return cookies. Also I was try before download insert command cy.setCookie()
If you could help how to resolve my problem or maybe smb also I dont close issue. If needs some addition information pls ask me
