### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [Xvier/cypress-downloadfile#25]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by Xvier** [comment]
@admah Thank you very much, I will look into the update guide.

**Comment by ViktorijaFilipov** [comment]
Supporting this. Please let us know when we can start using it with Cypress 10. Thank you!

**Comment by Xvier** [comment]
@ViktorijaFilipov The plugin works out of the box with Cypress 10, the only thing you need to change is the config.

So to have it working if you migrate to cypress 10 and use the cypress.config.js

Then the setup looks like this.

```js
const { defineConfig } = require('cypress')
const {downloadFile} = require('cypress-downloadfile/lib/addPlugin')

module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
         on('task', {downloadFile})
      })
    }
  }
})
```

The support file import stays the same.

If you need more help please let me know
