### ISSUE TITLE
How to download when URL is not available 

### ISSUE THREAD

**Issue by tgoswami013** [Xvier/cypress-downloadfile#26]
Files are generally downloaded at the user's click of a button or some other action. URL is not always available. Can we download a file using this plugin by clicking on a button?

By default, files are downloaded to the downloads folder in Cypress, but is there any way we can perform the action using this plugin?

**Comment by Xvier** [comment]
@tgoswami013, this plugin is not created with that mindset that you dont know what the URL is. 
The reason I created this plugin was that in the beginning Cypress did not have a normal download function. 

If you want to just click on a link and then the url is generated, then you are better of using the native Cypress function.

**Comment by AriEncarnacion** [comment]
@tgoswami013 @Xvier I know this issue is closed, but I'm using a workaround like this:
```JavaScript
cy.findByText(/myButtonText/i) // From cypress-testing-library
    .should('have.attr', 'href')
    .then(href => {
       const downloadUrl = String(href)
       cy.downloadFile(downloadUrl, 'mydownloads', 'example.jpg')
    })
```

In general, if the link exists, there should be someway to access it through Cypress queries.
