### ISSUE TITLE
No way to provide additional header information to request

### ISSUE THREAD

**Issue by nickbetsworth** [Xvier/cypress-downloadfile#3]
With the current API I'm unable to set additional header information on the request.

This is problematic for me as `request` does not have a user-agent by default, and my application requires a user-agent to be present.

**Comment by Xvier** [comment]
I will try and look into it this week. I hope i can get back to you and help you

**Comment by Xvier** [comment]
@nickbetsworth In version 1.1.5 you can now add a User-Agent string.
