### ISSUE TITLE
function error

### ISSUE THREAD

**Issue by PlutoRaven** [Xvier/cypress-downloadfile#30]
Hi Xvier, I am trying the same steps and running the same sample test given above, but I get an error stating “cy.downloadFile is not a function”. 
I'm using Cypress version 10.10.0 
Thanks

**Comment by Xvier** [comment]
@PlutoRaven Can you show a bit of your code?

**Comment by SarahJane87** [comment]
Add `require('cypress-downloadfile/lib/downloadFileCommand');` to cypress/support/commands.js
