### ISSUE TITLE
Error: Cannot find module 'cypress-downloadfile/lib/downloadFileCommand'

### ISSUE THREAD

**Issue by llech** [Xvier/cypress-downloadfile#5]
Error: Cannot find module 'cypress-downloadfile/lib/downloadFileCommand' after upgrading cypress-downloadfile to version 1.1.0

**To Reproduce**
1. Upgrade cypress-downloadfile in package.json from 1.0.1 to 1.1.0 
2. Run your tests

**Expected behavior**
Should work ;) 

**Desktop**
 - OS: Linux Ubuntu
 - Browser: chrome

It looks like a trivial issue. The file name lib/downloadFileCommand was capitalized, and the README on npm site was not updated.

**Comment by Xvier** [comment]
Fixed this in version 1.1.1
