### ISSUE TITLE
Plugin doesn't work on migrating Cypress to 4.2.0 or above

### ISSUE THREAD

**Issue by sllshrm** [Xvier/cypress-downloadfile#8]
**Describe the bug**
Cypress has removed the deprecated **request** package from 4.2.0, and because of this package being dependent on that, breaks Cypress.

**To Reproduce**
1. Update cypress to 4.2.0 or above
2. Run/Open Cypress

**Expected behavior**
Cypress should run test cases/UI should appear without any errors

**Screenshots**
![Capture](https://user-images.githubusercontent.com/41990985/78051059-caa21880-739a-11ea-8d74-bdaf0c53c1e1.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin Version 1.1.5
 - Cypress Version 4.3.0

**Comment by Xvier** [comment]
I will look into it

**Comment by sllshrm** [comment]
Forgot to add stack-trace which might help you. Thanks for looking into it!

![Capture](https://user-images.githubusercontent.com/41990985/78110112-18109b00-7418-11ea-8733-f260901c8b65.PNG)

Relevant Cypress ticket:
https://github.com/cypress-io/cypress/pull/6679

**Comment by plasmaboyer** [comment]
you have to execute  manually npm install request
The dependency is not downloaded

**Comment by morficus** [comment]
@Xvier  - take a look at this PR from Cypress: https://github.com/cypress-io/cypress/commit/d810950379ca4744748f8ec1735376af06db2441


Cypress forked the "request" library and republished it as `@cypress/request`, so this is why your plugin is failing in the 4.2 version.

But "request" has [officially been deprecated](https://www.npmjs.com/package/request). So it might be wise to move away from it an use one of [the many still active alternatives](https://github.com/request/request/issues/3143)

**Comment by Xvier** [comment]
@morficus Thx for looking into it, i will check your pr later this week. Its a bit hectic now at work because of all the corona stuff so i hope to have reviewed your code by wednesday

**Comment by sllshrm** [comment]
@Xvier 
Did you get a chance to look at this?

**Comment by Xvier** [comment]
@sllshrm No i didnt, but i cleared up some time tomorrow morning to review, test and if all works approve it.

**Comment by Xvier** [comment]
@sllshrm I created a new version 1.2.0 so if you update to this version it should work.

**Comment by sllshrm** [comment]
Thanks man, appreciate it!
